Using docker compose in cd workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,7 +7,7 @@ on:
 env:
   IMAGE_NAME: bravo680/onecoffee-admin-web
   IMAGE_TAG: latest
-  PORT: 3001
+  WEB_FOLDER: /var/www/onecoffee-admin-web
 jobs:
   Lint:
     runs-on: ubuntu-latest
@@ -55,15 +55,15 @@ jobs:
         run: |
           echo "$SSH_KEY" > key.pem
           chmod 600 key.pem
-          ssh -tt -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST "     
-            CONTAINER_ID=$(docker ps -q --filter ancestor=$IMAGE_NAME:$IMAGE_TAG)
-            if [ ! -z "$CONTAINER_ID" ]; then
-              echo "Stopping existing container: $CONTAINER_ID"
-              docker stop $CONTAINER_ID
-            else
-              echo "No running containers found for image $IMAGE_NAME:$IMAGE_TAG"
-            fi
-            docker rmi -f $IMAGE_NAME:$IMAGE_TAG || echo "No previous image to remove"
-            docker pull $IMAGE_NAME:$IMAGE_TAG
-            docker run -d -p $PORT:80 $IMAGE_NAME:$IMAGE_TAG
-          "
+          ssh -tt -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST \
+          "cd $WEB_FOLDER && \
+          if [ -f docker-compose.yaml ]; then \
+            echo \"docker-compose.yml exists, proceeding with deployment.\" && \
+            docker compose down && \
+            docker rmi -f $IMAGE_NAME:$IMAGE_TAG && \
+            docker pull $IMAGE_NAME:$IMAGE_TAG && \
+            docker compose up -d; \
+          else \
+            echo \"docker-compose.yaml not found in $WEB_FOLDER\" && \
+            exit 1; \
+          fi"
